### ISSUE TITLE
De-provisioning addon fails

### ISSUE THREAD

**Issue by MingZhang-PS** [kyma-project/helm-broker#106] opened 2020-06-17 07:30 UTC
**Description**
I can provisioning my addon via "Service Management UI" successfully, everything works well. But when de-provisioning the addon instance via clicking the "delete" button. It gives error message like:
`Deprovision call failed; received error response from broker: Status: 400; ErrorMessage: while checking if instance is already deprovisioned: while getting instance operations from storage: while decoding returned entities: while decoding DSO: gob: name not registered for interface: "map[string]interface {}"; Description: ; ResponseError: <nil>`

I also check the helm broker log via `kubectl logs helm-broker-6c4b4cccb7-8l99f -c broker -n kyma-system`. The log is shown as below, no much useful information.
```
{"level":"info","log":{"message":"started handling request","method":"DELETE","remote":"127.0.0.1:40424","request":"/ns/extension-installer/v2/service_instances/e9654c9e-dc81-4485-ba34-f734190671f0?accepts_incomplete=true\u0026plan_id=e868f0ba-1074-42de-8db4-e0c3ea0fdbdb\u0026service_id=ca0ebdb6-216b-465f-8fdf-499f4aecfcce","request_id":"b8255fcc-4e97-40f1-b5fe-31be22050e94","time":"2020-06-15T02:47:12.398Z"}}
{"level":"warning","log":{"message":"Server responds with error: [HTTP 400]: [while checking if instance is already deprovisioned: while getting instance operations from storage: while decoding returned entities: while decoding DSO: gob: name not registered for interface: \"map[string]interface {}\"] []","service":"server","time":"2020-06-15T02:47:12.399Z"}}
{"level":"info","log":{"message":"completed handling request","method":"DELETE","remote":"127.0.0.1:40424","request":"/ns/extension-installer/v2/service_instances/e9654c9e-dc81-4485-ba34-f734190671f0?accepts_incomplete=true\u0026plan_id=e868f0ba-1074-42de-8db4-e0c3ea0fdbdb\u0026service_id=ca0ebdb6-216b-465f-8fdf-499f4aecfcce","request_id":"b8255fcc-4e97-40f1-b5fe-31be22050e94","size":251,"status":400,"time":"2020-06-15T02:47:12.399Z","took":1685488}}
{"level":"info","log":{"message":"started handling request","method":"DELETE","remote":"127.0.0.1:40424","request":"/ns/extension-installer/v2/service_instances/98932185-e267-4a3f-a669-b0f651550bb6?accepts_incomplete=true\u0026plan_id=e868f0ba-1074-42de-8db4-e0c3ea0fdbdb\u0026service_id=ca0ebdb6-216b-465f-8fdf-499f4aecfcce","request_id":"ae8f25d5-8cb8-496a-8631-fc6a6af0d51a","time":"2020-06-15T02:47:12.596Z"}}
{"level":"warning","log":{"message":"Server responds with error: [HTTP 400]: [while checking if instance is already deprovisioned: while getting instance operations from storage: while decoding returned entities: while decoding DSO: gob: name not registered for interface: \"map[string]interface {}\"] []","service":"server","time":"2020-06-15T02:47:12.597Z"}}
```
So may I know how to go on debugging? By the way, I didn't have such issue in Kyma 1.11.0 before

Kyma version: 1.12.0
Kyma cluster URL: https://console.kongfu.kaka.shoot.canary.k8s-hana.ondemand.com/
Provider: GCP
Addon repo: github.com/SAP-samples/fsm-extension-installer-kyma/addons/index.yaml

**Expected result**
Addon service instance can be deleted successfully

**Actual result**
Can't de-provisioning addon service instance 

**Steps to reproduce**

**Troubleshooting**

**Comment by MingZhang-PS** [comment] 2020-06-18 10:00
By the way, I can't even provisioning the [SAP offered addon](https://github.com/kyma-project/addons/blob/master/addons/index-testing.yaml) now, it stays pending with error log "Orphan mitigation was completed successfully"

**Comment by piotrmiskiewicz** [comment] 2020-07-06 13:04
Hint for bug fixing - check if the following line: ```gob.Register(map[string]interface{}{})``` in `decodeDSOToDM` method fixes the bug

**Comment by mszostok** [comment] 2020-07-15 12:07
Hi @MingZhang-PS 

> By the way, I can't even provisioning the SAP offered addon now, it stays pending with error log "Orphan mitigation was completed successfully". 

with the newest Kyma master (`master-d88b1359`) I was not able to reproduce that error. If you will run into that issue once again, please download logs from service-catalog-controller-manager, run:

```bash
kubectl logs $(kubectl get po -l app=service-catalog-catalog-controller-manager -n kyma-system --no-headers -o custom-columns=":metadata.name") -c controller-manager  > manager.logs
```

---
the problem with the `"map[string]interface {}"` was detected and fixed in [this PR](https://github.com/kyma-project/helm-broker/pull/118), fix will be available with new Kyma release 👍 

-- 

**Found issues**

GCP Classes do not have icon:
<img width="1750" alt="obraz" src="https://user-images.githubusercontent.com/17568639/87541138-14d8ac80-c6a1-11ea-9c70-08531737a2e4.png">

**Comment by MingZhang-PS** [comment] 2020-07-16 02:54
Hi @mszostok 
First, thanks for the PR! I will verify it when it is released.
Second, for the issue below
> By the way, I can't even provisioning the SAP offered addon now, it stays pending with error log "Orphan mitigation was completed successfully".

I reproduced and captured the log. Please aware the log is captured on my Kyma 1.12.0. I don't test it on the latest official release (1.13.0)

[manager.logs.TXT](https://github.com/kyma-project/helm-broker/files/4929035/manager.logs.TXT)

**Comment by mszostok** [comment] 2020-07-20 07:52
Hi,

Thanks for the logs. I've checked them and the error is exactly the same 
> controller_instance.go:1828] ServiceInstance "personal-i333451/testing-ming" v13157426: Error provisioning ServiceInstance of ServiceClass (K8S: "personal-i333451/faebbe18-0a84-11e9-ab14-d663bd873d94" ExternalName: "testing") at ClusterServiceBroker "helm-broker": Status: 500; ErrorMessage: while getting instance collection: while decoding DSO collection: gob: name not registered for interface: "map[string]interface {}"; Description: ; ResponseError: <nil>

if you will see such error then what you can do it as a workaround is always retrigger (Cluster)AddonsConfiguration synchronization

**Comment by mszostok** [comment] 2020-07-20 07:52
reopening as we need to bump helm-broker version in Kyma repo

**Closed** 2020-07-31 07:37 UTC
Labels: area/service-catalog, bug
