### ISSUE TITLE
Helm Broker catalog endpoint if refresh in each minute and class&plans metrics not scrapped

### ISSUE THREAD

**Issue by mszostok** [kyma-project/helm-broker#101] opened 2020-06-08 09:43 UTC
**Description**

From the Helm Broker Grafana charts we can see that the HelmBroker GetCatalog endpoint is called in each minute. Other brokers e.g. `minibroker` does not have such problems. We need to know if the metrics are wrong or the broker is really spammed. 

Additionally, service catalog does not return the number of service classes and plans for the helm broker on `/metrics` endpoint and they are also not visible on chart. In comparison when we register the `minibroker` then all class&plans are logged. 

<img width="1847" alt="obraz" src="https://user-images.githubusercontent.com/17568639/84015814-b1aa7a80-a97c-11ea-8ab9-fddbe55f3ee2.png">

Hint:
- check if metrics for namespaced and cluster-wide brokers are handled properly

**Comment by PK85** [comment] 2020-09-24 11:13
Probably liveness probe, please call him

**Comment by kjaksik** [comment] 2020-12-16 16:17
Hi @mszostok,
The frequent calls are caused by Helm Broker Controller's healthcheck mechanism.
Every 60 seconds new ClusterAssetGroup is created which triggers a RelistRequest on the Broker. The AssetGroup is then deleted and the process repeats one minute later. It was designed that way and If we want to change it we would have to think of another way of checking the controller liveliness. Only mitigation for that would be to increase the period between healtcheck calls.

We still have to look into the missing class and plans metrics.

**Comment by kjaksik** [comment] 2021-01-07 11:50
Yeah, so it was a bug on the Service Catalog metrics side, should be fixed by [#2873](https://github.com/kubernetes-sigs/service-catalog/pull/2873). Then a quick bump of Service Catalog and every broker in Kyma and the metrics should be working fine.

**Closed** 2021-01-18 08:06 UTC
Labels: bug
